version: "3"
services:
    
    frontend:
        container_name: frontend
        build: 
            context: ../
            dockerfile: ./dockerCompose/Dockerfile.web.prod.compose
        image: ganadara135/abbfront:latest
        ports:
            - "80:80"
        networks:
            - net-abb

volumes:
    rdb-data:
networks:
    net-abb: